
### Create a new user
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "email": "neda@gmail.com",
  "password": "adfl"
}

### Get a particular user
GET http://localhost:3000/auth/6
Content-Type: application/json

### Find all users  
GET http://localhost:3000/auth
Content-Type: application/json

### Find all users with the given ID
GET http://localhost:3000/auth?email=asdf@gmail.com
Content-Type: application/json

### Delete a user given id
DELETE http://localhost:3000/auth/5

### Update a user
PATCH http://localhost:3000/auth/3
Content-Type: application/json

{
  "email": "kian@gmail.com"
}