
### Create a new user
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "email": "hamid@gmail.com",
  "password": "adfkjl"
}

### Get a particular user
GET http://localhost:3000/auth/3
Content-Type: application/json

### Find all users with the given ID
GET http://localhost:3000/auth?email=adf@gmail.com
Content-Type: application/json

### Delete a user given id
DELETE http://localhost:3000/auth/5

### Update a user
PATCH http://localhost:3000/auth/234
Content-Type: application/json

{
  "email": "saeed@gmail.com"
}